/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaSorpresa;
import civitas.Jugador;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Rocío Barragán Moreno
 */
public class CasillaPanel extends javax.swing.JPanel {

    Casilla casilla;
    
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }
    
    void setCasilla(Casilla casilla, Casilla actual, Jugador jugador, int indice){
        this.casilla=casilla;
        
        if(casilla == actual){ //Si la casilla es la misma que la actual,resaltamos el borde de la casilla
        if(indice == 0){
            Border borde = BorderFactory.createLineBorder(Color.red, 4, true);
            nombre.setBorder(borde);
        }else if(indice == 1){
            Border borde = BorderFactory.createLineBorder(Color.green, 4, true);
            nombre.setBorder(borde);
        }else if(indice == 2){
            Border borde = BorderFactory.createLineBorder(Color.blue, 4, true);
            nombre.setBorder(borde);
        }else {
            Border borde = BorderFactory.createLineBorder(Color.yellow, 4, true);
            nombre.setBorder(borde);
        }
        }
        else{
            Border borde = BorderFactory.createLineBorder(Color.black, 1, false);
            nombre.setBorder(borde);
        }
        nombre.setText(this.casilla.getNombre());
        if(this.casilla.getNombre() == "SALIDA"){ //Ponemos distintos colores para los diferentes tipos de casillas
            nombre.setBackground(Color.YELLOW);
        }
        else if(this.casilla.getNombre() == "SORPRESA"){
            nombre.setBackground(Color.ORANGE);
        }
        else if(this.casilla.getNombre() == "PARKING"){
            nombre.setBackground(Color.MAGENTA);
        }
        else{
            Color colorCalle = new Color(161, 247, 212);
            nombre.setBackground(colorCalle);
        }
        if(this.casilla.getNombre().length() > 11){
            Font font = new Font("Lato Black", Font.BOLD, 14);
            nombre.setFont(font);
        }
        repaint();
        revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("C059", 1, 15)); // NOI18N
        nombre.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
