/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import civitas.Jugador;
import java.util.ArrayList;
import civitas.Casilla;
import civitas.CasillaCalle;

/**
 *
 * @author Rocío Barragán Moreno
 */
public class JugadorPanel extends javax.swing.JPanel {

    Jugador jugador;
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }
    
    void setJugador(Jugador jugador){
        this.jugador=jugador;
        nombreTextField.setText(jugador.getNombre());
        saldoTextField.setText(Integer.toString((int) jugador.getSaldo()));
        
        if(jugador.esEspeculador()){
            esEspeculadorTextField.setText("SI");
        }
        else{
        esEspeculadorTextField.setText("NO");
        }
        
        rellenaPropiedades(jugador.getPropiedades());
        repaint();
        revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
        PropiedadPanel vistaPropiedad = new PropiedadPanel();
        vistaPropiedad.setPropiedad(t);
        propiedadesPanel.add(vistaPropiedad);
        vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        saldoLabel = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        esEspeculadorLabel = new javax.swing.JLabel();
        esEspeculadorTextField = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        nombreLabel.setText("Nombre:");
        add(nombreLabel);

        nombreTextField.setEditable(false);
        nombreTextField.setText("jTextField1");
        add(nombreTextField);

        saldoLabel.setText("Saldo:");
        add(saldoLabel);

        saldoTextField.setEditable(false);
        saldoTextField.setText("jTextField2");
        add(saldoTextField);

        esEspeculadorLabel.setText("Es especulador:");
        add(esEspeculadorLabel);

        esEspeculadorTextField.setEditable(false);
        esEspeculadorTextField.setText("jTextField3");
        add(esEspeculadorTextField);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        propiedadesPanel.setMinimumSize(new java.awt.Dimension(121, 121));
        propiedadesPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esEspeculadorLabel;
    private javax.swing.JTextField esEspeculadorTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JTextField saldoTextField;
    // End of variables declaration//GEN-END:variables
}
